import type { ReactNode } from "react";
import {
  ArrowRight,
  Bell,
  Building2,
  Check,
  ClipboardList,
  FileText,
  FolderKanban,
  LayoutDashboard,
  LockKeyhole,
  Megaphone,
  SearchCheck,
  Settings,
  ShieldCheck,
  TicketCheck,
  Users,
} from "lucide-react";
import { services, specialties, specialtySlug } from "@/lib/content";
import { authRoutes, portalRoutes } from "@/lib/routes";
import { AuditForm, AuthForm, ContactForm, FAQList, RoiCalculator, SearchExperience } from "./interactive";
import { cn, tw } from "./tw";

const titleFromSlug = (slug: string) => slug.split("-").map((word) => word[0]?.toUpperCase() + word.slice(1)).join(" ");

export function InnerPage({ segments }: { segments: string[] }) {
  const [root, second] = segments;
  if (authRoutes.includes(root)) return <AuthPage mode={root} />;
  if (root === "portal" || portalRoutes.includes(root)) return <PortalPage module={root === "portal" ? second || "dashboard" : root} />;
  if (root === "services" && second) return <ServicePage slug={second} />;
  if (root === "specialties" && second) return <SpecialtyPage slug={second} />;
  if (root === "roi-calculator") return <ToolPage eyebrow="Growth planning tool" title="Calculate your growth potential" description="Explore a transparent, range-based planning estimate. Adjust the assumptions and use the result to guide a more useful strategy conversation."><RoiCalculator full /></ToolPage>;
  if (root === "free-audit") return <ToolPage eyebrow="Free practice audit" title="Find the clearest growth gap" description="Answer three business-level questions to prepare a focused audit brief. Do not include patient or medical information."><AuditForm /></ToolPage>;
  if (root === "contact") return <ToolPage eyebrow="Contact Doctors Marketing Agency" title="Start with the business challenge" description="Tell us what you are building, fixing or trying to understand. The frontend is ready for a secure lead endpoint."><ContactForm /></ToolPage>;
  if (root === "search") return <ToolPage eyebrow="Search" title="Find the right solution" description="Search the current service and specialty content index."><SearchExperience /></ToolPage>;
  if (root === "faq") return <StandardPage eyebrow="Frequently asked questions" title="Clear answers before we begin" intro="A practical overview of our model, boundaries and integration status."><FAQList /></StandardPage>;
  if (["privacy-policy", "terms-of-service", "accessibility"].includes(root)) return <LegalPage type={root} />;
  if (root === "services") return <ServicesOverview />;
  if (root === "specialties") return <SpecialtiesOverview />;
  if (root === "case-studies") return <CaseStudies detail={second} />;
  if (root === "blog" || root === "resources") return <ContentLibrary type={root} detail={second} />;
  if (root === "pricing") return <PricingPage />;
  if (root === "about") return <AboutPage />;
  return <NotFound />;
}

function InnerHero({ eyebrow, title, description, action = "Book a free strategy call" }: { eyebrow: string; title: string; description: string; action?: string }) {
  return <section className="bg-[radial-gradient(circle_at_92%_10%,#d5e7ff,transparent_38%),radial-gradient(circle_at_3%_100%,#ffe3d1,transparent_38%),#f8fafc] py-28 max-[820px]:py-20"><div className={cn(tw.container, "grid min-h-[460px] grid-cols-[1.25fr_.75fr] items-center gap-14 max-[820px]:min-h-0 max-[820px]:grid-cols-1")}><div><span className={tw.eyebrow}>{eyebrow}</span><h1 className={cn(tw.h1, "my-6 max-w-4xl")}>{title}</h1><p className="max-w-2xl text-lg text-muted">{description}</p><div className="mt-8 flex flex-wrap gap-3"><a className={cn(tw.button, tw.primary)} href="/contact">{action} <ArrowRight size={16} /></a><a className={cn(tw.button, tw.ghost)} href="/free-audit">Request a free audit</a></div></div><div className="relative h-[360px] rounded-full border border-blue-200 max-[820px]:hidden"><div className="absolute inset-14 rounded-full border border-blue-100" /><span className="absolute top-1/2 left-1/2 grid size-18 -translate-1/2 place-items-center rounded-full bg-brand text-white"><ShieldCheck size={28} /></span>{["top-[16%] left-[21%] bg-accent","right-[9%] top-[48%] bg-white","bottom-[7%] left-[43%] bg-brand"].map((classes) => <i className={cn("absolute size-7 rounded-full shadow-md", classes)} key={classes} />)}</div></div></section>;
}

function StandardPage({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: ReactNode }) {
  return <><InnerHero eyebrow={eyebrow} title={title} description={intro} /><section className={tw.section}><div className={cn(tw.container, "max-w-4xl")}>{children}</div></section><InnerCta /></>;
}

function ToolPage({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) {
  return <section className="min-h-[760px] bg-[radial-gradient(circle_at_90%_0,#d7e8ff,transparent_32%),radial-gradient(circle_at_0_95%,#ffe2cf,transparent_36%),#f8fafc] py-24"><div className={cn(tw.container, "grid grid-cols-[.75fr_1.25fr] items-center gap-16 max-[900px]:grid-cols-1 max-[900px]:gap-9")}><div><a className="mb-9 block text-sm text-muted" href="/">← Home</a><span className={tw.eyebrow}>{eyebrow}</span><h1 className={cn(tw.h1, "my-6")}>{title}</h1><p className="text-muted">{description}</p><div className="mt-7 flex gap-3 rounded-xl border border-line bg-white/70 p-4 text-xs"><LockKeyhole className="shrink-0 text-brand" size={19} /><span>Frontend adapter only. Do not enter sensitive health or patient information.</span></div></div><div>{children}</div></div></section>;
}

function ServicesOverview() {
  return <><InnerHero eyebrow="Connected capabilities" title="Healthcare growth works better as a system." description="Choose the focused expertise you need today while keeping every service aligned to the wider patient and operational journey." action="Find the right service" /><section className={tw.section}><div className={cn(tw.container, "grid gap-2.5")}>{services.map((service, index) => { const Icon = service.icon; return <a className="grid grid-cols-[3rem_2rem_1fr_auto] items-center gap-5 rounded-2xl border border-line p-6 hover:border-blue-200 hover:bg-soft-blue max-[600px]:grid-cols-[2rem_1fr_auto]" href={`/services/${service.slug}`} key={service.slug}><span className="text-xs text-muted">{String(index + 1).padStart(2, "0")}</span><Icon className="text-brand max-[600px]:hidden" size={23} /><div><h2 className="text-xl font-extrabold">{service.title}</h2><p className="mt-1 text-sm text-muted">{service.description}</p></div><ArrowRight size={20} /></a> })}</div></section><InnerCta /></>;
}

function ServicePage({ slug }: { slug: string }) {
  const service = services.find((item) => item.slug === slug);
  if (!service) return <NotFound />;
  const Icon = service.icon;
  return <><InnerHero eyebrow={service.short} title={service.title} description={service.description} action={slug.includes("software") ? "Discuss your software" : "Discuss your growth plan"} /><section className={tw.section}><div className={cn(tw.container, "grid grid-cols-[1.25fr_.75fr] items-start gap-20 max-[820px]:grid-cols-1 max-[820px]:gap-9")}><div><span className={tw.eyebrow}>What the engagement covers</span><h2 className={cn(tw.h2, "my-6")}>Built around your current stage—not a fixed package.</h2><p className="max-w-2xl text-muted">We begin by clarifying business objectives, patient-facing needs, internal ownership and the systems already in place. The roadmap is then shaped around the highest-value gaps.</p><div className="mt-8 grid grid-cols-2 gap-2.5 max-[540px]:grid-cols-1">{service.outcomes.map((outcome) => <div className="flex items-center gap-2.5 rounded-xl bg-slate-50 p-4" key={outcome}><Check className="text-brand" size={17} /><span>{outcome}</span></div>)}</div></div><aside className="sticky top-28 rounded-3xl border border-line bg-soft-blue p-9 max-[820px]:static"><span className={tw.icon}><Icon size={24} /></span><h3 className="mt-6 text-2xl font-extrabold">A connected service boundary</h3><p className="my-4 text-muted">This capability can run independently or connect with positioning, website, acquisition, follow-up and reporting work.</p><a className={tw.textLink} href="/services">See all capabilities <ArrowRight size={15} /></a></aside></div></section><section className={cn(tw.section, "bg-slate-50")}><div className={cn(tw.container, "grid grid-cols-3 gap-4 max-[700px]:grid-cols-1")}>{[["01","Diagnose","Review the audience, existing assets, data quality and team constraints."],["02","Build","Create the strategy and production system with clear approvals."],["03","Improve","Measure useful signals and refine what the team can sustain."]].map(([number,title,copy]) => <article className={cn(tw.panel, "p-8")} key={number}><span className="text-xs text-brand">{number}</span><h3 className="mt-9 text-2xl font-extrabold">{title}</h3><p className="mt-3 text-sm text-muted">{copy}</p></article>)}</div></section><InnerCta /></>;
}

function SpecialtiesOverview() {
  return <><InnerHero eyebrow="Healthcare focus" title="Growth systems shaped around specialty context." description="Every specialty has a different patient decision, service mix, reputation dynamic and capacity constraint. The strategy should reflect that." action="Request a specialty audit" /><section className={tw.section}><div className={cn(tw.container, "grid grid-cols-3 gap-4 max-[850px]:grid-cols-2 max-[600px]:grid-cols-1")}>{specialties.map((specialty) => <a className="flex min-h-56 flex-col rounded-3xl border border-line p-7 transition hover:-translate-y-1 hover:shadow-card" href={`/specialties/${specialtySlug(specialty)}`} key={specialty}><span className={tw.icon}><Building2 size={20} /></span><h2 className="mt-7 text-xl font-extrabold">{specialty}</h2><p className="mt-2 flex-1 text-sm text-muted">Brand, website, search and inquiry journeys tailored to this specialty context.</p><ArrowRight className="self-end text-brand" size={18} /></a>)}</div></section><InnerCta /></>;
}

function SpecialtyPage({ slug }: { slug: string }) {
  const specialty = specialties.find((item) => specialtySlug(item) === slug) || titleFromSlug(slug);
  return <><InnerHero eyebrow={`${specialty} growth`} title={`A clearer digital path for ${specialty.toLowerCase()}.`} description="Help prospective patients understand services, build trust and take the next appropriate step—without inflated clinical or commercial claims." action="Request a specialty growth audit" /><section className={tw.section}><div className={cn(tw.container, "grid grid-cols-[1.25fr_.75fr] items-start gap-20 max-[820px]:grid-cols-1 max-[820px]:gap-9")}><div><span className={tw.eyebrow}>Specialty growth priorities</span><h2 className={cn(tw.h2, "my-6")}>Start with how people choose and how your team responds.</h2><div className="mt-8 grid">{[[SearchCheck,"Be visible for the right needs","Map high-intent searches to useful service content and local context."],[ShieldCheck,"Communicate with credibility","Explain expertise, process and next steps in clear patient-friendly language."],[Users,"Improve inquiry handoffs","Clarify ownership, response workflows and qualification boundaries."]].map(([Icon,title,copy]) => { const PriorityIcon = Icon as typeof SearchCheck; return <article className="grid grid-cols-[auto_1fr] gap-4 border-b border-line py-5" key={title as string}><PriorityIcon className="text-brand" /><div><h3 className="text-xl font-extrabold">{title as string}</h3><p className="mt-2 text-sm text-muted">{copy as string}</p></div></article> })}</div></div><aside className="rounded-3xl border border-line bg-soft-warm p-9"><h3 className="text-2xl font-extrabold">Recommended starting point</h3><p className="my-4 text-muted">A focused specialty audit covering positioning, search visibility, website conversion and inquiry operations.</p><a className={cn(tw.button, tw.secondary)} href="/free-audit">Start the audit <ArrowRight size={16} /></a></aside></div></section><InnerCta /></>;
}

function AboutPage() {
  return <><InnerHero eyebrow="About the agency" title="Healthcare growth, design and technology at one table." description="Doctors Marketing Agency is positioned as a long-term strategic partner for healthcare organizations navigating visibility, patient experience and digital operations." /><section className={tw.section}><div className={cn(tw.container, "grid grid-cols-[.8fr_1.2fr] gap-24 max-[820px]:grid-cols-1 max-[820px]:gap-8")}><div><span className={tw.eyebrow}>Our point of view</span><h2 className={cn(tw.h2, "mt-6")}>Good growth begins with clarity.</h2></div><div className="space-y-5 text-lg text-muted"><p>Healthcare organizations often buy isolated deliverables: a logo, a website, a campaign or a CRM. The patient and the team experience all of them as one connected system.</p><p>Our model brings strategy, content, experience design, marketing and software thinking together early—so every investment has a clearer purpose and owner.</p><div className="flex flex-wrap gap-2 pt-4">{["Human communication","Responsible evidence","Maintainable systems","Transparent boundaries"].map((item) => <span className="rounded-full border border-line px-3.5 py-2 text-xs text-navy" key={item}>{item}</span>)}</div></div></div></section><section className={cn(tw.section, "bg-slate-50")}><div className={tw.container}><span className={tw.eyebrow}>Team transparency</span><h2 className={cn(tw.h2, "my-6")}>People and credentials will be published after verification.</h2><p className="text-muted">[TEAM PROFILE REQUIRED] [CREDENTIAL REVIEW REQUIRED] [FINAL CONTACT DETAILS REQUIRED]</p></div></section><InnerCta /></>;
}

function CaseStudies({ detail }: { detail?: string }) {
  if (detail) return <StandardPage eyebrow="Case study architecture" title={titleFromSlug(detail)} intro="This case study remains unpublished until the client, context and result sources are approved."><div className="rounded-3xl border border-line bg-slate-50 p-10"><ShieldCheck className="text-brand" size={30} /><h2 className="mt-6 text-3xl font-extrabold">Evidence review in progress</h2><p className="mt-3 text-muted">[CLIENT APPROVAL REQUIRED] [VERIFIED RESULT REQUIRED] [LICENSED IMAGE REQUIRED]</p><h3 className="mt-8 text-xl font-extrabold">Planned case-study structure</h3><ul className="mt-4 list-disc space-y-2 pl-5"><li>Business context and starting constraints</li><li>Approved strategy and scope</li><li>Implementation decisions</li><li>Verified outcomes and source notes</li><li>What the team learned</li></ul></div></StandardPage>;
  return <StandardPage eyebrow="Evidence architecture" title="Proof, published responsibly." intro="This library is ready for verified healthcare growth stories. No fictional clients, logos or performance metrics are shown."><div className="grid grid-cols-3 gap-4 max-[760px]:grid-cols-1">{["Patient journey","Healthcare platform","Multi-location growth"].map((item) => <article className={cn(tw.panel, "min-h-64 p-7")} key={item}><span className="text-xs font-bold text-accent">Verification pending</span><h2 className="mt-10 text-2xl font-extrabold">{item}</h2><p className="mt-3 text-sm text-muted">Client context, scope and outcomes will appear after source and approval review.</p><a className={cn(tw.textLink, "mt-6")} href={`/case-studies/${item.toLowerCase().replaceAll(" ", "-")}`}>View evidence structure <ArrowRight size={15} /></a></article>)}</div></StandardPage>;
}

const resources = [["medical-website-brief","Website planning","A practical brief for your next medical website"],["patient-inquiry-audit","Lead experience","Where patient inquiries quietly lose momentum"],["healthcare-ai-checklist","Responsible AI","A safer checklist for non-clinical automation"],["local-search-foundations","Medical SEO","Local search foundations for specialist practices"]];

function ContentLibrary({ type, detail }: { type: string; detail?: string }) {
  const library = type === "blog" ? "Insights" : "Resources";
  if (detail) return <StandardPage eyebrow={`${library} article`} title={titleFromSlug(detail)} intro="A practical, non-clinical guide for healthcare leaders planning a clearer growth system."><article className="mx-auto max-w-3xl"><p className="text-xl text-navy">Strong healthcare growth work begins by connecting the decision patients need to make with the operating reality of the organization.</p><h2 className="mt-12 text-3xl font-extrabold">Begin with the journey, not the channel</h2><p className="mt-4 text-muted">Map how someone discovers the service, decides whether it feels relevant, asks a question and receives a useful response. This exposes gaps that a new campaign alone cannot solve.</p><h2 className="mt-12 text-3xl font-extrabold">Give every handoff an owner</h2><p className="mt-4 text-muted">Clarify what the website should do, where inquiries go, when a person steps in and which signals the team will review. Keep sensitive medical data outside ordinary marketing workflows.</p><div className="mt-10 flex gap-3 rounded-xl bg-soft-blue p-5"><ShieldCheck className="shrink-0 text-brand" size={22} /><p className="text-muted">This content is general business information and not medical, legal or compliance advice.</p></div></article></StandardPage>;
  return <StandardPage eyebrow="Healthcare intelligence" title={`${library} for clearer decisions.`} intro="Practical thinking for leaders working across healthcare brand, growth, websites and technology."><div className="grid grid-cols-2 gap-4 max-[700px]:grid-cols-1">{resources.map(([slug,tag,title]) => <a className={cn(tw.panel, "flex min-h-64 flex-col p-7 transition hover:-translate-y-1")} href={`/${type}/${slug}`} key={slug}><span className="text-xs font-bold text-brand">{tag}</span><h2 className="mt-10 text-2xl font-extrabold">{title}</h2><p className="mt-3 flex-1 text-sm text-muted">Explore the questions, decisions and handoffs that make this work more useful.</p><strong className="inline-flex items-center gap-1.5 text-sm">Read article <ArrowRight size={15} /></strong></a>)}</div></StandardPage>;
}

function PricingPage() {
  const plans = [["Focused engagement","Audit or strategy sprint","For a defined question, opportunity or planning decision.","[FINAL PRICE REQUIRED]"],["Connected growth","Ongoing growth partnership","For coordinated brand, acquisition, website and reporting work.","Custom monthly scope"],["Technology build","Website or software project","For defined discovery, design and implementation phases.","Custom project scope"]];
  return <StandardPage eyebrow="Engagement options" title="Scope before price. Clarity before commitment." intro="Healthcare projects vary substantially by markets, locations, integrations, governance and internal capacity. We provide a scoped proposal after discovery."><div className="grid grid-cols-3 items-stretch gap-4 max-[760px]:grid-cols-1">{plans.map(([tag,title,copy,price], index) => <article className={cn("flex min-h-72 flex-col rounded-3xl border border-line p-8", index === 1 ? "-translate-y-4 bg-deep text-white max-[760px]:translate-y-0" : "bg-white")} key={tag}><span className="text-xs font-bold text-accent">{tag}</span><h2 className="mt-12 text-2xl font-extrabold">{title}</h2><p className={cn("mt-3 flex-1 text-sm", index === 1 ? "text-slate-300" : "text-muted")}>{copy}</p><strong>{price}</strong></article>)}</div></StandardPage>;
}

function LegalPage({ type }: { type: string }) {
  return <StandardPage eyebrow="Legal and accessibility" title={titleFromSlug(type)} intro="A publication-ready structure is provided below. Final policy wording requires legal review before launch."><div className="max-w-3xl"><p className="rounded-xl bg-soft-warm p-4 text-xs">[LEGAL REVIEW REQUIRED] Last frontend revision: August 5, 2026</p>{[["Purpose and scope","This website presents business services for healthcare organizations. It does not provide medical advice, clinical services or emergency support."],["Information handling","Ordinary marketing forms should collect only necessary business contact information. Visitors should not submit diagnoses, records, treatment information or other sensitive patient data."],["Third-party services","Booking, analytics, authentication, newsletter and assistant services remain integration boundaries until configured and reviewed."],["Questions","[FINAL CONTACT DETAILS REQUIRED]"]].map(([title,copy]) => <div key={title}><h2 className="mt-10 text-2xl font-extrabold">{title}</h2><p className="mt-3 text-muted">{copy}</p></div>)}</div></StandardPage>;
}

function AuthPage({ mode }: { mode: string }) {
  return <section className="grid min-h-screen grid-cols-[1.1fr_.9fr] bg-slate-50 max-[820px]:grid-cols-1"><div className="relative flex flex-col justify-center overflow-hidden bg-deep p-[9vw] text-white max-[820px]:hidden"><span className={tw.eyebrowDark}>Client workspace</span><h2 className={cn(tw.h1, "my-6")}>One clear view of projects, decisions and progress.</h2><p className="max-w-xl text-slate-300">This interface is an integration-ready preview. No account or client data is persisted.</p><div className="absolute -right-24 -bottom-24 size-[420px] rounded-full border border-white/10"><span className="absolute inset-14 rounded-full border border-white/10" /><span className="absolute inset-28 rounded-full bg-brand/20" /></div></div><AuthForm mode={mode} /></section>;
}

const portalIcons = [LayoutDashboard, Users, Building2, FolderKanban, ClipboardList, Megaphone, SearchCheck, FileText, TicketCheck, Bell, Settings];
function PortalPage({ module }: { module: string }) {
  const current = titleFromSlug(module || "dashboard");
  return <section className="grid min-h-screen grid-cols-[240px_1fr] bg-slate-100 max-[820px]:grid-cols-[76px_1fr] max-[540px]:block"><aside className="flex flex-col bg-footer p-4 text-white max-[540px]:hidden"><a className="mb-7 flex items-center gap-2.5 px-2" href="/"><span className="grid size-11 place-items-center rounded-xl bg-brand font-black shadow-[inset_-7px_-7px_0_rgba(255,138,61,.85)]">DM</span><strong className="text-xs max-[820px]:hidden">Client workspace</strong></a><nav className="grid flex-1 gap-1">{portalRoutes.slice(0, 11).map((item,index) => { const Icon = portalIcons[index % portalIcons.length]; return <a className={cn("flex items-center gap-2.5 rounded-lg px-3 py-2.5 text-xs text-slate-400 hover:text-white max-[820px]:justify-center max-[820px]:text-[0]", item === module && "bg-[#123459] text-white")} href={`/portal/${item}`} key={item}><Icon size={17} />{titleFromSlug(item)}</a> })}</nav><a className="p-2 text-xs text-slate-400 max-[820px]:hidden" href="/">Return to public site</a></aside><div className="min-w-0 p-9 max-[820px]:p-5"><header className="flex items-center justify-between"><div><small className="text-muted">Frontend preview</small><h1 className="text-3xl font-extrabold">{current}</h1></div><button className="relative grid size-11 place-items-center rounded-xl border border-line bg-white"><Bell size={19} /><span className="absolute -top-1.5 -right-1.5 grid size-5 place-items-center rounded-full bg-brand text-[.6rem] text-white">0</span></button></header><div className="my-7 flex items-center gap-2.5 rounded-xl bg-blue-100 p-3 text-xs text-blue-800"><ShieldCheck size={18} />Structured fixture interface — no live client data, persistence or authentication is connected.</div><div className="grid grid-cols-3 gap-3.5 max-[760px]:grid-cols-1">{[["Items requiring review","—","Connect project API"],["Open decisions","—","Connect approvals API"],["Next meeting","Not scheduled","Connect booking API"]].map(([label,value,note]) => <article className={cn(tw.panel, "grid p-5")} key={label}><span className="text-xs text-muted">{label}</span><strong className="my-5 text-2xl">{value}</strong><small className="text-muted">{note}</small></article>)}</div><div className={cn(tw.panel, "mt-4 p-6")}><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-extrabold">{current} workspace</h2><button className={cn(tw.button, tw.primary)}>Create request</button></div><div className="flex min-h-96 flex-col items-center justify-center text-center text-muted"><FolderKanban size={28} /><h3 className="mt-4 text-lg font-extrabold text-navy">No connected records yet</h3><p>This module is ready for a typed backend adapter and organization permissions.</p><a className={cn(tw.textLink, "mt-4")} href="/contact">Discuss portal integration <ArrowRight size={15} /></a></div></div></div></section>;
}

function InnerCta() { return <section className="bg-footer py-16 text-white"><div className={cn(tw.container, "flex items-center justify-between gap-10 rounded-3xl bg-[#0c2949] p-12 max-[760px]:flex-col max-[760px]:items-start max-[540px]:p-7")}><div><span className={tw.eyebrowDark}>A useful next step</span><h2 className="mt-6 max-w-4xl text-[clamp(2rem,3.6vw,3.5rem)] leading-tight font-extrabold">Bring us the challenge. We’ll help clarify the system around it.</h2></div><a className={cn(tw.button, tw.secondary, "shrink-0")} href="/contact">Book a free strategy call <ArrowRight size={16} /></a></div></section>; }

function NotFound() { return <section className="flex min-h-[80vh] flex-col items-center justify-center bg-soft-blue px-5 text-center"><span className="font-display text-3xl italic text-brand">404</span><h1 className={cn(tw.h1, "my-5")}>This route needs a better handoff.</h1><p className="text-muted">The page may have moved, or the requested content has not been published.</p><div className="mt-6 flex gap-3"><a className={cn(tw.button, tw.primary)} href="/">Return home</a><a className={cn(tw.button, tw.ghost)} href="/search">Search the site</a></div></section>; }
