import Image from "next/image";
import {
  ArrowRight,
  BarChart3,
  Bot,
  CalendarCheck2,
  Check,
  ClipboardCheck,
  Gauge,
  HeartHandshake,
  LineChart,
  MessagesSquare,
  Route,
  SearchCheck,
  ShieldCheck,
  Sparkles,
  Workflow,
} from "lucide-react";
import { services, specialties, specialtySlug } from "@/lib/content";
import { AudienceSwitcher, ContactForm, FAQList, RoiCalculator } from "./interactive";
import { cn, tw } from "./tw";

const process = [
  ["01", "Diagnose", "Clarify your positioning, markets, services, capacity and current patient journey."],
  ["02", "Design", "Shape the brand, website and campaign system around a coherent growth thesis."],
  ["03", "Connect", "Link inquiry paths, follow-up workflows and reporting boundaries."],
  ["04", "Improve", "Review useful signals, test responsibly and strengthen weak handoffs."],
  ["05", "Scale", "Extend what works to new services, locations or technology initiatives."],
];

export function HomePage() {
  return (
    <>
      <section className="pt-6 pb-16">
        <div className={cn(tw.container, "grid grid-cols-[1.65fr_1fr] gap-4 max-[820px]:grid-cols-1")}>
          <div className="flex min-h-[650px] flex-col items-start justify-center rounded-[30px] bg-[radial-gradient(circle_at_95%_0,rgba(198,221,255,.95),transparent_43%),radial-gradient(circle_at_6%_93%,rgba(255,218,190,.75),transparent_38%),linear-gradient(135deg,#f8fafc,#eef5ff)] p-[clamp(2.25rem,5vw,4.5rem)] max-[820px]:min-h-0 max-[540px]:rounded-3xl max-[540px]:p-6">
            <span className={tw.eyebrow}>Human-led healthcare growth systems</span>
            <h1 className={cn(tw.h1, "my-6 max-w-4xl")}><span className="block font-display font-normal italic text-accent">Become the first choice</span> for the patients and partners you serve.</h1>
            <p className="mb-7 max-w-2xl text-lg text-muted">Doctors Marketing Agency connects brand, patient acquisition, websites and healthcare technology into one practical growth system.</p>
            <div className="flex flex-wrap gap-3 max-[540px]:w-full max-[540px]:flex-col"><a className={cn(tw.button, tw.primary)} href="/contact">Book a free strategy call <ArrowRight size={17} /></a><a className={cn(tw.button, tw.secondary)} href="/free-audit">Request a practice audit <ArrowRight size={17} /></a></div>
            <div className="mt-9 flex items-center gap-4"><div className="flex">{[SearchCheck, Workflow, BarChart3].map((Icon, index) => <span className={cn("grid size-9 place-items-center rounded-full border-2 border-soft-blue bg-white text-brand", index > 0 && "-ml-1.5")} key={index}><Icon size={16} /></span>)}</div><p className="m-0 text-xs leading-relaxed text-muted"><strong className="text-navy">Connected by design</strong><br />Strategy, experience and systems in one plan.</p></div>
          </div>
          <div className="grid min-w-0 grid-rows-[1fr_190px] gap-4 max-[820px]:grid-rows-[470px_150px] max-[540px]:grid-rows-[420px_140px]">
            <div className="relative min-h-[440px] overflow-hidden rounded-[30px] bg-slate-200"><Image className="object-cover object-[center_28%]" src="/images/doctor-hero.png" alt="Physician in a bright contemporary clinic holding a tablet" fill priority sizes="(max-width: 900px) 100vw, 38vw" /></div>
            <div className="flex flex-col justify-between overflow-hidden rounded-3xl bg-soft-blue p-7"><div className="grid"><span>From first search</span><strong className="text-xl">to confident next steps.</strong></div><div className="flex items-center justify-center text-brand">{[SearchCheck, MessagesSquare, CalendarCheck2].map((Icon, index) => <div className="contents" key={index}>{index > 0 && <i className="h-px flex-1 bg-blue-200" />}<span className="grid size-11 place-items-center rounded-full bg-white shadow-md"><Icon size={16} /></span></div>)}</div></div>
          </div>
        </div>
      </section>

      <section className="border-y border-line py-8"><div className={cn(tw.container, "flex items-center justify-between gap-8 max-[820px]:flex-col max-[820px]:items-start")}><span className="text-xs tracking-[.12em] uppercase text-muted">Built for the healthcare ecosystem</span><div className="flex flex-wrap gap-8 text-sm font-bold text-slate-500 max-[540px]:gap-4"><strong>Doctors</strong><strong>Specialist clinics</strong><strong>Hospitals</strong><strong>Diagnostic groups</strong><strong>Health technology</strong></div></div></section>

      <section className={tw.section}><div className={tw.container}><span className={tw.eyebrow}>A partner on your side of the table</span><HeadingSplit title={<>Not another disconnected agency.<br />Your <em className={tw.display}>healthcare growth partner.</em></>}><p className="text-muted">Patients rarely experience your brand, website, campaign and follow-up as separate departments. We help your team design them as one journey.</p><a className={tw.textLink} href="/about">How we work <ArrowRight size={16} /></a></HeadingSplit><div className="mt-14 grid grid-cols-[1.15fr_.85fr] items-center gap-16 max-[820px]:grid-cols-1 max-[820px]:gap-9"><div className="relative min-h-[490px] overflow-hidden rounded-[30px] max-[820px]:min-h-[360px]"><Image className="object-cover" src="/images/clinic-strategy.png" alt="Physician and clinic operations leader reviewing strategy together" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div><span className="inline-grid size-12 place-items-center rounded-2xl bg-soft-warm text-accent"><Route size={24} /></span><h3 className="my-6 text-4xl font-extrabold">Replace scattered activity with a clear route.</h3><p className="text-muted">We begin with the commercial and operational reality: what you offer, who should choose it, where inquiries are lost and which systems your team can sustain.</p><ul className="my-7 grid gap-3">{["One shared growth thesis", "Clear patient-facing communication", "Useful reporting and ownership"].map((item) => <li className="flex items-center gap-2.5" key={item}><Check className="text-brand" size={16} />{item}</li>)}</ul><a className={cn(tw.button, tw.primary)} href="/contact">Talk about your goals <ArrowRight size={16} /></a></div></div></div></section>

      <section className={cn(tw.section, "bg-slate-50/70")}><div className={tw.container}><SectionHeading eyebrow="Complete service ecosystem" title={<>Build the parts that matter.<br /><em className={tw.display}>Connect the whole journey.</em></>} copy="Engage one focused service or coordinate a broader transformation across growth and technology." /><div className="grid grid-cols-3 gap-4 max-[1050px]:grid-cols-2 max-[620px]:grid-cols-1">{services.map((service, index) => { const Icon = service.icon; return <a className={cn("flex min-h-[290px] flex-col rounded-3xl border border-line p-7 transition hover:-translate-y-1 hover:shadow-card", index % 4 === 1 ? "bg-soft-blue" : index % 4 === 2 ? "bg-soft-warm" : "bg-white")} href={`/services/${service.slug}`} key={service.slug}><div className="flex items-center justify-between"><span className="text-xs text-muted">{String(index + 1).padStart(2, "0")}</span><span className={tw.icon}><Icon size={21} /></span></div><h3 className="mt-12 mb-3 text-xl font-extrabold">{service.title}</h3><p className="flex-1 text-sm text-muted">{service.description}</p><span className={tw.textLink}>Explore service <ArrowRight size={15} /></span></a> })}</div><div className="mt-10 flex justify-center"><a className={cn(tw.button, tw.dark)} href="/services">Explore our complete capabilities <ArrowRight size={16} /></a></div></div></section>

      <section className={tw.section}><div className={cn(tw.container, "rounded-[30px] bg-[radial-gradient(circle_at_70%_15%,rgba(214,229,255,.9),transparent_42%),#f7f9fc] p-14 max-[820px]:p-6")}><div className="mb-14 grid grid-cols-[1.2fr_.8fr] items-end gap-16 max-[820px]:grid-cols-1 max-[820px]:gap-5"><div><span className={tw.eyebrow}>A calm, accountable process</span><h2 className={cn(tw.h2, "mt-6")}>From <em className={tw.display}>diagnosis</em> to a system your team can run.</h2></div><div><p className="text-muted">Each stage ends with a decision, a useful artifact and a clear owner—so momentum never depends on mystery.</p><a className={cn(tw.button, tw.secondary, "mt-4")} href="/contact">Start a conversation <ArrowRight size={16} /></a></div></div><div className="grid grid-cols-[1.1fr_.7fr] gap-12 max-[820px]:grid-cols-1"><div>{process.map(([number, title, copy]) => <div className="grid grid-cols-[2rem_1fr] gap-4 border-b border-line py-5" key={number}><span className="pt-1 text-xs text-muted">{number}</span><div><h3 className="text-2xl font-extrabold">{title}</h3><p className="mt-2 text-sm text-muted">{copy}</p></div></div>)}</div><div className="relative min-h-[650px] overflow-hidden rounded-3xl max-[820px]:min-h-[500px]"><Image className="object-cover object-[50%_35%]" src="/images/practice-call.png" alt="Clinic owner speaking on the phone and taking notes" fill sizes="(max-width: 800px) 100vw, 36vw" /></div></div></div></section>

      <section className={tw.section}><div className={tw.container}><SectionHeading eyebrow="Responsible evidence" title={<>Results should speak for <em className={tw.display}>themselves.</em></>} copy="We publish outcomes only after source review and client approval. Until then, explore the types of improvement our systems are designed to measure." /><div className="grid grid-cols-3 gap-4 max-[820px]:grid-cols-1">{[[SearchCheck,"Visibility","Higher-intent discovery","Track search presence, qualified traffic and service-page actions.","from-blue-500 to-blue-950"],[CalendarCheck2,"Conversion","Clearer inquiry paths","Measure lead quality, response times and appointment handoffs.","from-orange-400 to-orange-950"],[Gauge,"Operations","More useful systems","Review workflow adoption, task ownership and reporting clarity.","from-slate-500 to-slate-950"]].map(([Icon,label,title,copy,gradient]) => { const ResultIcon = Icon as typeof SearchCheck; return <article className={cn("flex min-h-[370px] flex-col justify-between rounded-3xl bg-gradient-to-br p-8 text-white", gradient as string)} key={label as string}><ResultIcon className="size-13 rounded-2xl bg-white/15 p-3" /><div><span className="text-xs font-bold tracking-widest text-orange-200 uppercase">{label as string}</span><h3 className="my-2 text-2xl font-extrabold">{title as string}</h3><p className="text-sm text-slate-200">{copy as string}</p></div></article> })}</div><div className="mt-4 flex items-center gap-2.5 rounded-xl border border-line p-4 text-xs text-muted max-[640px]:flex-wrap"><ShieldCheck className="text-brand" size={18} /><span>Case-study metrics remain unpublished until verified. <strong>[VERIFIED RESULT REQUIRED]</strong></span><a className={cn(tw.textLink, "ml-auto max-[640px]:ml-0 max-[640px]:w-full")} href="/case-studies">View evidence framework <ArrowRight size={15} /></a></div></div></section>

      <section className={cn(tw.section, "bg-[radial-gradient(circle_at_95%_45%,#dceaff,transparent_35%),radial-gradient(circle_at_8%_70%,#ffe8d8,transparent_36%)]")}><div className={tw.container}><span className={tw.eyebrow}>What makes the model different</span><h2 className={cn(tw.h2, "mt-6 mb-16")}>Built for healthcare.<br />Designed for <em className={tw.display}>useful progress.</em></h2><div className="grid grid-cols-3 gap-12 text-center max-[820px]:grid-cols-1 max-[820px]:gap-8">{[[HeartHandshake,"Human before automation","Technology supports clear, respectful communication and responsible team handoffs."],[LineChart,"Decisions before dashboards","Reporting is designed around the choices your team actually needs to make."],[ShieldCheck,"Trust before tactics","Claims, consent and patient-facing language receive the scrutiny healthcare requires."]].map(([Icon,title,copy],index) => { const FeatureIcon = Icon as typeof HeartHandshake; return <article className="px-5" key={title as string}><span className={cn("mx-auto mb-6 grid size-20 place-items-center", index === 2 ? "text-accent" : "text-brand")}><FeatureIcon className="size-16 stroke-[1.3]" /></span><h3 className="text-2xl font-extrabold">{title as string}</h3><p className="mt-3 text-sm text-muted">{copy as string}</p></article> })}</div></div></section>

      <section className={tw.section}><div className={cn(tw.container, "grid grid-cols-[.85fr_1.15fr] items-center gap-14 overflow-hidden rounded-[30px] bg-deep p-16 text-white max-[950px]:grid-cols-1 max-[820px]:p-8")}><div><span className={tw.eyebrowDark}>Healthcare technology capability</span><h2 className={cn(tw.h2, "my-6")}>Software that follows the way your team <em className="font-display font-normal italic text-accent">actually works.</em></h2><p className="text-slate-300">From lead-management workflows to custom healthcare platforms, we translate operational reality into clear interfaces and integration boundaries.</p><ul className="my-7 grid gap-3 text-slate-200">{["Medical CRM and lead workflows", "Custom portal and platform UX", "Automation with human escalation", "Typed integration boundaries"].map((item) => <li className="flex gap-2.5" key={item}><Check className="text-blue-400" size={16} />{item}</li>)}</ul><a className={cn(tw.button, tw.light)} href="/services/healthcare-software-solutions">Discuss your medical software <ArrowRight size={16} /></a></div><ProductPreview /></div></section>

      <section className={tw.section}><div className={tw.container}><HeadingSplit title={<>Different organizations.<br /><em className={tw.display}>One connected approach.</em></>}><p className="text-muted">Every engagement is shaped around the audience, buying journey, operating model and level of clinical complexity involved.</p></HeadingSplit><AudienceSwitcher /><div className="mt-5 flex flex-wrap gap-2.5">{specialties.slice(0, 8).map((specialty) => <a className="inline-flex items-center gap-1.5 rounded-full border border-line px-3.5 py-2 text-xs hover:border-brand/40 hover:text-brand" href={`/specialties/${specialtySlug(specialty)}`} key={specialty}>{specialty}<ArrowRight size={14} /></a>)}</div></div></section>

      <section className={cn(tw.section, "bg-slate-50/80")}><div className={tw.container}><HeadingSplit title={<>Model the <em className={tw.display}>economics</em> before the campaign.</>} eyebrow="Transparent planning"><p className="text-muted">Use a simple range-based estimate to explore how lead quality, conversion and capacity affect your growth plan.</p></HeadingSplit><RoiCalculator /><div className="mt-8 flex justify-center"><a className={tw.textLink} href="/roi-calculator">Open the full calculator <ArrowRight size={16} /></a></div></div></section>

      <section className={cn(tw.section, "bg-slate-100/80")}><div className={tw.container}><span className={tw.eyebrow}>Client trust</span><h2 className={cn(tw.h2, "mt-6 mb-12")}>Proof deserves <em className={tw.display}>verification.</em></h2><div className="grid grid-cols-[1fr_1fr_.8fr] gap-4 max-[900px]:grid-cols-2 max-[600px]:grid-cols-1">{["Approved client feedback will be published here with source, role and organization context.","This space is intentionally transparent rather than filled with fictional social proof."].map((copy) => <article className={cn(tw.panel, "min-h-64 p-8")} key={copy}><Sparkles className="text-accent" size={21} /><h3 className="mt-9 text-lg font-extrabold">[VERIFIED TESTIMONIAL REQUIRED]</h3><p className="mt-3 text-sm text-muted">{copy}</p></article>)}<article className="flex min-h-64 flex-col justify-between rounded-3xl bg-deep p-8 text-white max-[900px]:col-span-full max-[600px]:col-span-1"><h3 className="text-2xl font-extrabold">Have a project that needs a more connected approach?</h3><a className={cn(tw.button, tw.primary, "w-fit")} href="/contact">Let’s discuss it <ArrowRight size={16} /></a></article></div></div></section>

      <section className={tw.section}><div className={tw.container}><HeadingSplit title={<>Ideas your team can <em className={tw.display}>use.</em></>} eyebrow="Practical resources"><a className={tw.textLink} href="/resources">Explore all resources <ArrowRight size={16} /></a></HeadingSplit><div className="grid grid-cols-3 gap-4 max-[820px]:grid-cols-1">{[["Website planning","A practical brief for your next medical website","Questions to align leadership, marketing and operations before design begins.","medical-website-brief"],["Lead experience","Where patient inquiries quietly lose momentum","A framework for reviewing response time, ownership and follow-up gaps.","patient-inquiry-audit"],["Responsible AI","A safer checklist for non-clinical automation","Define scope, escalation, privacy and maintenance before introducing an assistant.","healthcare-ai-checklist"]].map(([tag,title,copy,slug]) => <a className={cn(tw.panel, "flex min-h-64 flex-col p-7 transition hover:-translate-y-1")} href={`/resources/${slug}`} key={slug}><span className="text-xs font-extrabold text-brand">{tag}</span><h3 className="mt-10 mb-3 text-2xl font-extrabold">{title}</h3><p className="flex-1 text-sm text-muted">{copy}</p><strong className="inline-flex items-center gap-1.5 text-sm">Read guide <ArrowRight size={15} /></strong></a>)}</div></div></section>

      <section className="bg-[radial-gradient(circle_at_90%_0,#67a8ff,transparent_36%),radial-gradient(circle_at_0_100%,#ffd4b9,transparent_38%),#eaf3ff] py-28"><div className={cn(tw.container, "grid grid-cols-2 items-center gap-16 max-[820px]:grid-cols-1 max-[820px]:gap-9")}><div><span className={tw.eyebrow}>Start with a useful conversation</span><h2 className={cn(tw.h2, "my-6")}>Let’s build a clearer path to your next stage of growth.</h2><p className="max-w-xl text-muted">Share the business challenge—not patient information—and we’ll route your request to the right capability.</p><div className="mt-7 grid gap-2.5">{["No obligation or inflated promises","A focused 30-minute conversation","Clear next steps and ownership"].map((item) => <span className="flex items-center gap-2.5 text-sm" key={item}><Check className="text-brand" size={16} />{item}</span>)}</div></div><ContactForm /></div></section>

      <section className="bg-footer py-16 text-white"><div className={cn(tw.container, "grid min-h-[430px] grid-cols-[1.2fr_.8fr] items-center gap-8 overflow-hidden rounded-[30px] border border-white/10 bg-[#0c2949] p-14 max-[820px]:grid-cols-1 max-[540px]:p-7")}><div><span className={tw.eyebrowDark}>The future of healthcare growth</span><h2 className={cn(tw.h2, "my-6")}>Because healthcare growth deserves a system—<em className="font-display font-normal italic text-accent">not guesswork.</em></h2><p className="max-w-2xl text-slate-300">Bring brand, acquisition, technology and operations into one calm, accountable roadmap.</p><div className="mt-7 flex flex-wrap gap-3 max-[540px]:flex-col"><a className={cn(tw.button, tw.primary)} href="/contact">Book a free strategy call <ArrowRight size={17} /></a><a className={cn(tw.button, tw.secondary)} href="/free-audit">Start with an audit <ArrowRight size={17} /></a></div></div><OrbitGraphic /></div></section>

      <section className={tw.section}><div className={tw.container}><HeadingSplit title={<>Questions before the <em className={tw.display}>first conversation?</em></>}><a className={tw.textLink} href="/faq">View all FAQs <ArrowRight size={16} /></a></HeadingSplit><FAQList limit={3} /></div></section>
    </>
  );
}

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: React.ReactNode; copy: string }) { return <div className="mb-14 max-w-4xl"><span className={tw.eyebrow}>{eyebrow}</span><h2 className={cn(tw.h2, "my-5")}>{title}</h2><p className="max-w-2xl text-muted">{copy}</p></div>; }

function HeadingSplit({ eyebrow, title, children }: { eyebrow?: string; title: React.ReactNode; children: React.ReactNode }) { return <div className="mb-14 grid grid-cols-[1.35fr_.65fr] items-end gap-16 max-[820px]:grid-cols-1 max-[820px]:gap-5"><div>{eyebrow && <span className={tw.eyebrow}>{eyebrow}</span>}<h2 className={cn(tw.h2, eyebrow && "mt-5")}>{title}</h2></div><div className="grid gap-4 pb-2">{children}</div></div>; }

function ProductPreview() { return <div className="min-w-0 rotate-2 overflow-hidden rounded-2xl border-7 border-[#102b4c] bg-slate-50 text-navy shadow-[0_30px_70px_rgba(0,0,0,.28)] max-[950px]:rotate-0"><div className="flex h-12 items-center justify-between border-b border-line px-4"><span className="grid size-8 place-items-center rounded-lg bg-brand text-[.65rem] font-black text-white">DM</span><div className="flex gap-1"><i className="size-2 rounded-full bg-slate-300" /><i className="size-2 rounded-full bg-slate-300" /><i className="size-2 rounded-full bg-slate-300" /></div></div><div className="grid min-h-96 grid-cols-[130px_1fr] max-[540px]:grid-cols-1"><aside className="grid content-start gap-1 bg-soft-blue p-3 max-[540px]:hidden">{[[BarChart3,"Overview"],[MessagesSquare,"Inquiries"],[Workflow,"Workflows"],[ClipboardCheck,"Approvals"]].map(([Icon,label],index) => { const NavIcon = Icon as typeof BarChart3; return <span className={cn("flex items-center gap-2 rounded-lg p-2 text-[.65rem]", index === 0 && "bg-white text-brand")} key={label as string}><NavIcon size={15} />{label as string}</span> })}</aside><div className="min-w-0 p-6"><div className="flex justify-between"><div className="grid"><small className="text-muted">Growth workspace</small><strong>Team overview</strong></div><button className="h-fit rounded-lg border border-line bg-white px-2 py-1 text-[.6rem]">Current month</button></div><div className="my-5 grid grid-cols-2 gap-2.5">{[["Qualified inquiries","—","Connect data source"],["Response workflow","Ready","Adapter configured"]].map(([label,value,note]) => <div className="grid rounded-xl border border-line bg-white p-4" key={label}><span className="text-[.6rem] text-muted">{label}</span><strong className="text-xl">{value}</strong><small className="text-[.55rem] text-slate-400">{note}</small></div>)}</div><div className="flex h-44 flex-col rounded-xl border border-line bg-white p-5"><div className="flex flex-1 items-end gap-2">{[32,55,43,70,62,87,78].map((height) => <i className="flex-1 rounded-t bg-gradient-to-b from-blue-400 to-blue-100" style={{ height: `${height}%` }} key={height} />)}</div><span className="mt-2 text-[.55rem] text-muted">Illustrative interface — no live client data</span></div></div></div></div>; }

function OrbitGraphic() { return <div className="relative h-80 max-[820px]:hidden"><div className="absolute inset-5 rounded-full border border-blue-300/25" /><div className="absolute inset-16 rounded-full border border-blue-300/25" /><span className="absolute top-1/2 left-1/2 grid size-18 -translate-1/2 place-items-center rounded-full bg-brand shadow-lg"><Bot size={34} /></span><span className="absolute top-3 left-1/2 grid size-12 place-items-center rounded-full bg-white text-brand"><SearchCheck size={20} /></span><span className="absolute bottom-6 left-[15%] grid size-12 place-items-center rounded-full bg-white text-brand"><CalendarCheck2 size={20} /></span><span className="absolute right-[5%] bottom-10 grid size-12 place-items-center rounded-full bg-white text-brand"><LineChart size={20} /></span></div>; }
